language: c++
compiler: gcc
env:
  global:
    - GCC_VERSION="4.9" 
before_install:
  - export CHECKOUT_PATH=`pwd`;
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
script:
  - echo "hello Travis CI!"
  - echo "//Some useful changes..." >> blocks/manu343726/try-biicode-travisci/main.cpp
  - tail blocks/manu343726/try-biicode-travisci/main.cpp
deploy:
  provider: biicode
  user: manu343726
  password:
    secure: jgfnN4eqgMxJW9JNNqLux2Ad55U8ybPEXcVsc3wnpyzolCPi42r6204dDILpuliN8qYEHyN3C9pKq94kK6Ew2oSuPCRZj83LlsqRK3X6mns5w4ObY42IOaE0wafhDkavPCd9WV+NrOBHP35niZE/S83rf0Dx/LR7aoVn8NKQt8A=
  on:
    repo: Manu343726/try-biicode-travisci
